w5d1/RedditClone/config/routes.rb
Rails.application.routes.draw do

  resources :users, only:[:index, :show, :new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]

  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create]

end

w5d1/RedditClone/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :author_id, :post_id, presence: true

  belongs_to :author, class_name: :User
  belongs_to :post

  belongs_to :parent_comment,
    foreign_key: :parent_comment_id,
    class_name: :Comment

  has_many :child_comments,
    foreign_key: :parent_comment_id,
    class_name: :Comment
    
end

w5d1/RedditClone/app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :subs, :author_id, presence: true

  belongs_to :author,
    class_name: 'User',
    foreign_key: :author_id

  has_many :postsubs, dependent: :destroy, inverse_of: :post, class_name: :PostSub, foreign_key: :post_id

  has_many :subs, through: :postsubs

  has_many :comments 

end

w5d1/RedditClone/app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  validates :post, :sub, presence: true

  belongs_to :post
  belongs_to :sub
end

w5d1/RedditClone/app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :moderator_id, presence: true

  belongs_to :moderator,
    class_name: 'User'

  has_many :postsubs, dependent: :destroy, inverse_of: :sub, class_name: :PostSub, foreign_key: :sub_id
  has_many :posts, through: :postsubs

end

w5d1/RedditClone/app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: {minimum: 4, message: "Password has to have at least 4 characters"}, allow_nil: true

  has_many :subs,
    foreign_key: :moderator_id

  has_many :posts,
    foreign_key: :author_id

  has_many :comments,
    foreign_key: :author_id,
    class_name: :Comment


  after_initialize :ensure_session_token
  attr_reader :password

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credential(username, password)
    @user = User.find_by(username: username)
    if @user && @user.is_password?(password)
      @user
    else
      nil
    end
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

w5d1/RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :require_user

  def require_user
    redirect_to new_session_url if current_user.nil?
  end

  def sign_in(user)
    session[:session_token] = user.reset_session_token!
  end

  def sign_out
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end


end

w5d1/RedditClone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    render :new
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_url(@comment.post_id)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to new_post_comment_url
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :author_id, :post_id)
  end
end

w5d1/RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user, only: [:new, :create, :edit, :update]

  def show
    @post = Post.find_by(id: params[:id])
    render :show
  end

  def edit
    @post = Post.find_by(id: params[:id])
    render :edit
  end

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, :author_id, sub_ids: [])
  end

end

w5d1/RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credential(params[:user][:username], params[:user][:password])
    if @user
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ["Invalid username or password"]
      redirect_to new_session_url
    end
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end
end

w5d1/RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_user

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    render :show
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def update
    @sub = Sub.find_by(id: params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)
  end

end

w5d1/RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def index
    @users = User.all
    render :index
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

w5d1/RedditClone/app/helpers/application_helper.rb
module ApplicationHelper
end

w5d1/RedditClone/app/helpers/comments_helper.rb
module CommentsHelper
end

w5d1/RedditClone/app/helpers/posts_helper.rb
module PostsHelper
end

w5d1/RedditClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

w5d1/RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

w5d1/RedditClone/app/helpers/users_helper.rb
module UsersHelper
end

w5d1/RedditClone/app/views/posts/_postsform.html.erb
<% action_url = post.persisted? ? post_url(post) : posts_url %>
<% http_method = post.persisted? ? "PATCH" : "POST" %>


<form action="<%= action_url%>" method="POST">
  <% if post.persisted?  %>
  <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <input type="hidden" name="authenticity_token" value="form_authenticity_token">

  <label for="title">Title</label>
  <input id= "title" type="text" name="post[title]" value="<%= post.title %>">
  <br>

  <label for="url">Url</label>
  <input id= "url" type="text" name="post[url]" value="<%= post.url %>">
  <br>

  <label for="content">Content</label>
  <input id= "content" type="text" name="post[content]" value="<%= post.content %>">
  <br>

  <label for="sub">Choose a sub that you want to post to</label>
  <br>
  <input type="hidden" name="post[sub_ids][]" value="">
    <% Sub.all.each do |sub| %>
      <label for="sub"><%= sub.title %>
      <input type="checkbox"
            name="post[sub_ids][]"
            value= "<%= sub.id %>"
             <%= "checked" if post.sub_ids.include?(sub.id) %>>
      </label>
    <% end  %>
  <br>


  <input type="hidden" name="post[author_id]" value=" <%= current_user.id %>">

  <input type="submit" value=" <%= post.persisted? ? "Update!" : "Create!" %> ">

</form>

w5d1/RedditClone/app/views/posts/edit.html.erb
<h1>Edit Your Post</h1>

<%= render 'postsform', post:@post %>

w5d1/RedditClone/app/views/posts/new.html.erb
<h1>Make Your Post</h1>

<%= render 'postsform', post:@post %>

w5d1/RedditClone/app/views/posts/show.html.erb
<h1>This Is Your Post</h1>
<p>Title <%= @post.title %></p>
<p>url <%= @post.url %></p>
<p>Content <%= @post.content %></p>
<p>Subs <% @post.subs.each do |sub| %> <%= sub.title %> <% end %> </p>
<p>Author <%= @post.author.username %></p>
<p><%= link_to 'New Comment', new_post_comment_url(@post) %> </p>
<p>Comments: <% @post.comments.each do |comment| %>
  <%= comment.content %>
  <br>
  <% end %>
</p>

w5d1/RedditClone/app/views/subs/_subform.html.erb
<% action_url = sub.persisted? ? sub_url(sub) : subs_url %>
<% http_method = sub.persisted? ? "PATCH" : "POST" %>


<form action="<%= action_url%>" method="POST">
  <% if sub.persisted?  %>
  <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <input type="hidden" name="authenticity_token" value="form_authenticity_token">


  <label for="title">Title</label>
  <input id= "title" type="text" name="sub[title]" value="<%= sub.title %>">

  <label for="description">Description</label>
  <input id= "description" type="text" name="sub[description]" value="<%= sub.description %>">

  <input type="hidden" name="sub[moderator_id]" value=" <%= current_user.id %>">

  <input type="submit" value=" <%= sub.persisted? ? "Update!" : "Create!" %> ">

</form>

w5d1/RedditClone/app/views/subs/edit.html.erb
<h1>Edit Your Sub</h1>

<%= render "subform", sub:@sub %>

w5d1/RedditClone/app/views/subs/index.html.erb
<h1>This is all the subs!</h1>

<% @subs.each do |sub| %>
  <p>Title: <% sub.title %></p>
  <p>Description: <% sub.description %></p>
<% end  %>

w5d1/RedditClone/app/views/subs/new.html.erb
<h1>Make Your Sub</h1>

<%= render 'subform', sub:@sub %>

w5d1/RedditClone/app/views/subs/show.html.erb
<h1>This is your sub</h1>

<%= @sub.title %>
<br>
<%= @sub.description %>

w5d1/RedditClone/app/views/users/index.html.erb
<h1>This is all of the users!</h1>

<p> <% @users.each do |user|  %>
  <%= user.username %>
  <% end %>

</p>

w5d1/RedditClone/app/views/users/new.html.erb
<h1>Sign up page!</h1>

<%= render 'shared/form', action:'sign up', url: users_url %>

w5d1/RedditClone/app/views/users/show.html.erb
<h1>This is your account</h1>

<p> Username: <%= @user.username %> </p>
<p> Your sub: <% @user.subs.each do |sub| %>
  <%= link_to "#{sub.title}", edit_sub_url %>
  <% end %>
</p>